title: EJ van Lanen 
logo: https://avatars.githubusercontent.com/u/172479670?s=400&u=b0b3c603fb9789292e01ff2816bf88fdec40fe83&v=4 # Use a relative path to logo image 
show_downloads: false
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin
email: ej@pm.me # Allow visitors to contact you
description: <a href="https://github.com/ejvanlanen/cv" class="name">EJ van Lanen</a><ul class="address"><li>ğŸ‡¦ğŸ‡¹ Vienna, Austria</li><li><a href="mailto:ej@pm.me">ğŸ“« ej@pm.me</a></li><li>ğŸ§‘â€ğŸ’» <a href="http://linkedin.com/in/ejvanlanen">linkedin</a></li></ul>
